server:
  port: 8090

spring:
  application:
    name: register-back
  #    Se comenta porque ya esta la configuracion en el microservico de CONFIG -- solo se pone cuando se hacen conexiones directas entre microservicios sin usar el msvc de config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  devtools:
    restart:
      enabled: false
#  security:
#    user:
#      name: haruto
#      password: 123456
#      roles: ADMIN

#Configuracion para que el mcvs de student se registre en EUREKA
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZOne: http://localhost:8761/eureka
